version: '3.8'

services:
    server:
      restart: always
      build:
        dockerfile: dockerfile
        context: .
      ports:
        - 80:8080
      environment:
        # - SERVER_ADDRESS=0.0.0.0
        - PORT=8080
        - QUIZ_PATH=/home/quiz_data
      volumes:
        - ../quiz_data:/home/quiz_data