FROM node:20 as builder

WORKDIR /usr/src/client
COPY package*.json ./
RUN npm install
RUN npm update --force
RUN npm rebuild node-sass
COPY . .

ARG REACT_APP_API_URL

RUN npm run build

FROM nginx:latest
COPY --from=builder /usr/src/client/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
