name: Build and deploy client on push to master

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: '' # TODO remove before proceeding to production

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install and rebuild dependencies
        working-directory: ./client/data-quiz
        run: |
          npm install
          npm rebuild node-sass

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        working-directory: ./client/data-quiz
        run: npm run build

      - name: Handle 404 fallback
        working-directory: ./client/data-quiz
        run: cp ./build/index.html ./build/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages
          FOLDER: client/data-quiz/build
          CLEAN: true

